name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Restore nx cache
        uses: actions/cache/restore@v3
        with:
          path: node_modules/.cache/nx
          key: nx-cache

      - name: Build testbed
        run: npm run testbed:build

      - name: Build graft-garden
        run: npm run graft-garden:build

      - name: Build use-engraft-demo
        run: npm run use-engraft-demo:build

      - name: Assemble output
        run: |
          mv packages/testbed/dist website/testbed
          mv packages/graft-garden/dist website/graft-garden
          mv packages/use-engraft-demo/dist website/use-engraft-demo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website

      - name: Clear nx cache
        id: clearRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.github.com/repos/${{ github.repository }}/actions/caches?key=nx-cache
          method: DELETE
          bearerToken: ${{ secrets.GITHUB_TOKEN }}
          customHeaders: '{"Accept": "application/vnd.github.v3+json"}'

      - name: Clear nx cache - show response
        run: |
          echo ${{ steps.clearRequest.outputs.response }}

      - name: Save nx cache
        uses: actions/cache/save@v3
        with:
          path: node_modules/.cache/nx
          key: nx-cache
